#홈페이지에서 API서비스 신청시 받은 Appkey, Appsecret 값 설정
APP_KEY: "PSOTfBpO6Qwj5FHIk4u2OhK4Qye1KEvo1YRc"
APP_SECRET: "hpzTyi05+lzp65mwZt51/S+D83siM/0ODBlXpG6tZJmYxPzlwqLiWlCNsOMJkpK8j254EBf34HFtzcPVL/eWPB9jZZ8z1hv6JqgkKAVOOrVD1d7gKDp567gS6igWRV77FhXOEJJAVE2aws36YDXyOC0TveQes2XPT8GjYyHM9hWZa8HbArI="

#계좌번호 앞 8자리
# CANO: "50089546"
CANO: "50099199"
#계좌번호 뒤 2자리
ACNT_PRDT_CD: ""

#ID: $0676788

#실전투자
#URL_BASE: "https://openapi.koreainvestment.com:9443"
#TR_ID_TYPE: "T"
#모의투자
URL_BASE: "https://openapivts.koreainvestment.com:29443"
TR_ID_TYPE: "V"

